[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    titleAddition = "The democratization of the Age of Aquarius is here."
    description = "The democratization of the Age of Aquarius is here. Wheel of Heaven is a knowledge base around the working theory that life on Earth was intelligently designed by an extraterrestrial civilization, the so-called Elohim."
    titleHome = "Wheel of Heaven"
    footer = "Made with ♥ in Switzerland using <a href=\"https://github.com/wheelofheaven/\">Github</a>, <a href=\"https://www.getzola.org/\">Zola</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
    alertText = ""

[de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
titleAddition = ""
    description = ""
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\">Github</a>, <a href=\"https://www.getzola.org/\">Zola</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
 
[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 20
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
titleAddition = ""
    description = ""
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\">Github</a>, <a href=\"https://www.getzola.org/\">Zola</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
    

[fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 15
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
titleAddition = ""
    description = ""
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\">Github</a>, <a href=\"https://www.getzola.org/\">Zola</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
      
[ja]
  languageName = "日本語"
  contentDir = "content/ja"
  weight = 35
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JA"
    titleAddition = "水瓶座の時代の民主化がここにあります。" 
    description = "水瓶座の時代の民主化がここにあります。 Wheel of Heaven は、地球上の生命は地球外文明、いわゆるエロヒムによって知的に設計されたという作業理論に関する知識ベースです。"
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\">Github</a>、<a href=\"https://www.getzola.org/\">Zola</a>、<a href=\"https://getdoks.org/\">Doks</a> を使用してスイスで ♥ で作成"
    alertText = ""

[ru]
  languageName = "Pусский"
  contentDir = "content/ru"
  weight = 15
  [ru.params]
    languageISO = "RU"
    languageTag = "ru-RU"
titleAddition = ""
    description = ""
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\">Github</a>, <a href=\"https://www.getzola.org/\">Zola</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
    
[zh]
  languageName = "中文"
  contentDir = "content/zh"
  weight = 15
  [zh.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
titleAddition = ""
    description = ""
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\">Github</a>, <a href=\"https://www.getzola.org/\">Zola</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
 
