[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    titleAddition = "The democratization of the Age of Aquarius starts here."
    description = "The democratization of the Age of Aquarius starts here. Wheel of Heaven is a knowledge base exploring the working hypothesis that life on Earth was intelligently designed by an extraterrestrial civilization, the so-called Elohim."
    titleHome = "Wheel of Heaven"
    footer = "Made with ♥ in Switzerland using <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, and <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Welcome to Wheel of Heaven. Please note this website is being still improved on a daily basis. 😊"

[de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
titleAddition = "Die Demokratisierung des Wassermannzeitalters ist hier."
    description = "Die Demokratisierung des Wassermannzeitalters ist hier. Wheel of Heaven ist eine sogenannte Knowledge Base, welche die Arbeitsthese vertritt, dass das Leben auf der Erde von einer außerirdischen Zivilisation, den sogenannten Elohim, geschaffen wurde."
    titleHome = "Wheel of Heaven"
    footer = "Made with ♥ in der Schweiz mithilfe von <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, und <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Willkommen bei Wheel of Heaven. Bitte beachte dass diese Website sich noch im Bau befindet. 😊"
 
[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 20
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
titleAddition = "La democratización de la Era de Acuario está aquí."
    description = "La democratización de la Era de Acuario está aquí. Wheel of Heaven es una knowledge base alrededor de la teoría de trabajo de que la vida en la tierra fue diseñada de manera inteligente por una civilización extraterrestre, el llamado Elohim."
    titleHome = "Wheel of Heaven"
    footer = "Made with ♥ en Suiza con <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, y <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Bienvenido a Wheel of Heaven. Tenga en cuenta que este sitio web aún se mejora a diario. 😊"
    

[fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 25
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
titleAddition = "La démocratisation de l'Âge du Verseau est là."
    description = "La démocratisation de l'Âge du Verseau est là. Wheel of Heaven est une knowledge base autour de la théorie de travail selon laquelle la vie sur terre a été intelligemment conçue par une civilisation extraterrestre, les soi-disant Elohim."
    titleHome = "Wheel of Heaven"
    footer = "Made with ♥ en Suisse avec <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, et <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Bienvenue chez Wheel of Heaven. Veuillez noter que ce site web est encore amélioré quotidiennement. 😊"
      
[ja]
  languageName = "日本語"
  contentDir = "content/ja"
  weight = 30
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JA"
    titleAddition = "水瓶座の時代の民主化がここにあります。" 
    description = "水瓶座の時代の民主化がここにあります。 Wheel of Heaven は、地球上の生命は地球外文明、いわゆるエロヒムによって知的に設計されたという作業理論に関する知識ベースです。"
    titleHome = "Wheel of Heaven"
    footer = "<a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>、<a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>、<a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a> を使用してスイスで ♥ で作成"
    alertText = "Wheel of Heaven へようこそ。 このウェブサイトは現在も日々改善されていることに注意してください。 😊"

[ru]
  languageName = "Pусский"
  contentDir = "content/ru"
  weight = 35
  [ru.params]
    languageISO = "RU"
    languageTag = "ru-RU"
titleAddition = "Демократизация эпохи Водолея здесь."
    description = "Демократизация эпохи Водолея здесь. Wheel of Heaven-это база знаний вокруг рабочей теории, что жизнь на Земле была разумно разработана внеземной цивилизацией, так называемым Elohim."
    titleHome = "Wheel of Heaven"
    footer = "Made with ♥ в Швейцарии c<a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, и <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Добро пожаловать в Wheel of Heaven. Обратите внимание, что этот веб-сайт ежедневно совершенствуется. 😊"
    
[zh]
  languageName = "中文"
  contentDir = "content/zh"
  weight = 40
  [zh.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
titleAddition = "水瓶座时代的民主化就在这里。"
    description = "水瓶座时代的民主化就在这里。 天堂是围绕着工作理论的知识基础，即地球上的生命是由外星文明智能设计的，即所谓的埃洛因（Elohim）。"
    titleHome = "Wheel of Heaven"
    footer = "使用<a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>，<a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a> 和 <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a> 在瑞士制造♥"
    alertText = "欢迎来到 Wheel of Heaven (“天轮”)。 请注意，该网站每天都在改进。 😊"
 
