# Meta Data for SEO

## Homepage
title = "Wheel of Heaven"
titleSeparator = "|"
titleAddition = "The democratization of the Age of Aquarius is here."
description = "The democratization of the Age of Aquarius is here. Wheel of Heaven is a knowledge base exploring the working hypothesis that life on Earth was intelligently designed by an extraterrestrial civilization we collectively remember as the Elohim."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["wheel-of-heaven.png"]
ogLocale = "en_US"
titleHome = "Wheel of Heaven"

## Twitter Cards
twitterSite = "wheelofheaven"
twitterCreator = "wheelofheaven"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Wheel of heaven"
schemaAuthor = "Zara Zinsfuss"
schemaAuthorTwitter = "zarazinsfuss"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/zarazinsfuss/"
schemaLocale = "en-US"
schemaLogo = "wheel-of-heaven-square.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "wheel-of-heaven.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/wheelofheaven/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "wheel-of-heaven-banner.jpg" # put in `./assets/images/`
fillImage = "900x507 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://github.com/wheelofheaven/\">Github</a>, <a class=\"text-muted\" href=\"https://getzola.org/\">Zola</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Zara Zinsfuss"

# Alert
alert = true
alertDismissable = true
alertText = "Welcome to Wheel of Heaven. Please note this website is still improved on a daily basis."

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/wheelofheaven/site"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = false

[sections]
  sectionNav = ["intro", "wiki", "resources"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = "ALL"
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = true
  multilingualMode = true
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
