# Meta Data for SEO

## Homepage
title = "Wheel of Heaven"
titleSeparator = "|"
titleAddition = "The democratization of the Age of Aquarius starts here."
description = "The democratization of the Age of Aquarius starts here. Wheel of Heaven is a knowledge base exploring the working hypothesis that life on Earth was intelligently designed by an extraterrestrial civilization we collectively remember as the Elohim."

## Open Graph
images = ["wheel-of-heaven.png"]
ogLocale = "en_US"
titleHome = "Wheel of Heaven"

## Twitter Cards
twitterSite = "wheelofheaven"
twitterCreator = "wheelofheaven"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Wheel of heaven"
schemaAuthor = "Zara Zinsfuss"
schemaAuthorTwitter = "zarazinsfuss"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/zarazinsfuss/"
schemaLocale = "en-US"
schemaLogo = "wheel-of-heaven-square.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "wheel-of-heaven.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/wheelofheaven/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "wheel-of-heaven-banner.jpg" # put in `./assets/images/`
fillImage = "900x507 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://github.com/wheelofheaven/\">Github</a>, <a class=\"text-muted\" href=\"https://getzola.org/\">Zola</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Zara Zinsfuss"

# Alert
alert = true
alertDismissable = true
alertText = ""

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/wheelofheaven/site"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = false

[sections]
  sectionNav = ["intro", "wiki", "resources", "medium", "topics"]

[options]
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  multilingualMode = true
  fullWidth = true
  navbarSticky = true

[menu]
  [menu.section]
    auto = true

[hyas_images]
  [hyas_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default) 
    loading = "lazy" 
    widths = [480, 576, 768, 1025, 1200, 1440] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "auto" # 100vw (default), 75vw, or auto for example
    process = "" # "fill 1600x900" or "fill 2100x900" for example
    lqip = "16x webp q20" # "16x webp q20" or "21x webp q20" for example