[[intro]]
  name = "En un mot"
  weight = 110
  identifier = "at-a-glance"
  url = "/intro/at-a-glance/"

[[intro]]
  name = "Chronologie"
  weight = 120
  identifier = "timeline"
  url = "/intro/timeline/"

[[intro]]
  name = "À retenir"
  weight = 130
  identifier = "take-aways"
  url = "/intro/take-aways/"

[[intro]]
  name = "À voir plus"
  weight = 140
  identifier = "see-more"
  url = "/intro/see-more/"

[[main]]
  name = "Intro"
  weight = 10
  identifier = "intro"
  url = "fr/intro/wheel-of-heaven/"

[[main]]
  name = "Wiki"
  url = "fr/wiki/"
  weight = 15

[[main]]
  name = "Articles"
  url = "fr/articles/"
  weight = 20

[[main]]
  name = "Resources"
  url = "fr/resources/"
  weight = 25

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/wheelofheaven/"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"24px\" height=\"24px\" viewBox=\"0 0 20 20\" version=\"1.1\"><g id=\"surface1\"><path style=\" stroke:currentColor;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;\" d=\"M 4.839844 1.980469 L 10.394531 9.171875 L 4.804688 15.019531 L 6.0625 15.019531 L 10.957031 9.898438 L 14.914062 15.019531 L 19.195312 15.019531 L 13.328125 7.421875 L 18.53125 1.980469 L 17.273438 1.980469 L 12.765625 6.695312 L 9.121094 1.980469 Z M 6.691406 2.878906 L 8.65625 2.878906 L 17.34375 14.121094 L 15.375 14.121094 Z M 6.691406 2.878906 \"/></g></svg>"
  url = "https://twitter.com/wheelofheaven"
  weight = 20

[[footer]]
  name = "Protection des données"
  url = "/privacy-policy/"
  weight = 10

[[footer]]
   name = "RSS"
   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-rss\"><path d=\"M4 11a9 9 0 0 1 9 9\"></path><path d=\"M4 4a16 16 0 0 1 16 16\"></path><circle cx=\"5\" cy=\"19\" r=\"1\"></circle></svg>"
   url = "/articles/index.xml"
   post = "v0.1.0"
   weight = 10
